config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
  
  get 'about', to: 'pages#about', as: 'about'
  post 'posts/:id/destroy', to: 'posts#destroy', as: "destroy_post"

  resources :users
  
  get "welcome", to: "home#index", as: "welcome"
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  get "explore", to: "explore#index", as: "explore"
  delete "sessions", to: "sessions#destroy", as: "logout"
  
  resources :posts do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    belongs_to :user
    
    validates :title, presence: true
    validates :body, presence: true

    # def self.find_user(x)
    #     user = User.find_by(id: x )
    #     user.name
    # end

    # def self.explore(&block)
    #     if block_given?
    #     self.all.each do |post|
    #         post.title
    #         post.body[0...10]
    #         block.call(post.user.id)
    #         end
    #     else
    #         puts "oops"
    #     end
    # end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_secure_password

  validates :user_name, presence: true, uniqueness: true
  validates :password, presence: true 
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :authenticated
  helper_method :logged_in?
 
    private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
      !current_user.nil?
    end
   
    def authenticated
      redirect_to login_path unless logged_in?
    end

      
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
       
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    private

    def comment_params
        params.require(:comment).permit(:username, :body).merge(user_id: session[:user_id])
    end
end

app/controllers/explore_controller.rb
class ExploreController < ApplicationController
    def index
        @posts = Post.all
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = 'About Us'
        @content = 'This is the about page'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    # before_action :post_params, except: [:index, :new, :create]

    def index
        if logged_in?
            @posts = @current_user.posts
          else
            redirect_to home_path 
        end
    end

    def new
        @post = Post.new()
    end

    def create
        if logged_in?
            @post = Post.create(post_params)
            @post.user_id = @current_user.id
            @post.save 
            
                if @post.valid?
                    redirect_to @post
                else 
                    flash[:errors] = @post.errors.full_messages
                    redirect_to new_post_path
                end
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        @post.update(post_params)
        redirect_to @post
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    
    # helper methods

    private

    def post_params
        params.require(:post).permit(:title, :body, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #skip_before_action :authenticated, only: [:new, :create, :destroy]

  def new
  end

  def create
    user = User.find_by(user_name: params[:user_name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path(user.id), notice: "Logged in!"
    else
      flash.now[:alert] = "Username or password is invalid"
      redirect_to login_path
    end
  end
  
  def destroy
    session[:user_id] = nil
    @current_user = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all 
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
            confirm_password
            session[:user_id] = @user.id
            redirect_to posts_path(@user)
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to @user
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end

    
    # helper methods

    private

    def user_params
        params.require(:user).permit(:user_name, :password, :password_confirmation)
    end

    def confirm_password
        if params[:user][:password] == params[:user][:password_confirmation]
        else
            flash[:error] = "Passwords do not match. Please try again."
            redirect_to new_user_path
        end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/explore_helper.rb
module ExploreHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/explore/index.html.erb
<div class="container">
<h1>Featured Jogs</h1>
    <% @posts.each do |post| %>
        <div class="card" style="width: 500px">
            <div class="col-lg-8">
                <div class="card-body">
                    <% if logged_in? %>
                        <strong><%= link_to post.title, post_path(post) %></strong><br>
                    <% else %>
                       <strong><%= link_to post.title, welcome_path %></strong>
                        <% flash[:error]="Member's only. Please Log in or Sign up."%>
                    <% end %>
                    "<%= post.body[0...15] %>..."<br>
                    <small><%= post.user.user_name %></small>
                </div>
            </div>
        </div>
        <br></br>
    <% end %>

app/views/home/index.html.erb
<body class="bg">
<center>
<% if flash[:error]%>
  <span style="color: red"><%= flash[:error] %></span>
  <% end %>
    <div class="card border-light text-black bg-transparent mb-3" style="width: 500px">
        <div class="card-body">
            <center>
                <p id=”notice”><%= notice %></p>
                <h1>Welcome to Jogger</h1>
                <p>An online journal</p>
                <br>
                <%= link_to "Sign Up", new_user_path, class: "btn btn-sm              btn-outline-primary" %>
                <br></br>
                <%= link_to "Log in", login_path, class: "btn btn-sm btn-outline-primary"%>
            </center>    
        </div>   
    </div>
<center>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Open+Sans:400i|Raleway:300i&display=swap"%>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-transparent mb-4">
    <a href="/" class="navbar-brand"><img src="https://image.flaticon.com/icons/svg/763/763812.svg" style="height:40px; width:auto;"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
    <% if logged_in? %>
      <li class="nav-item">
        <%= link_to "My Jogs", posts_path, class: "nav-link color" %>
      </li>
      <% end %>
       <li class="nav-item">
        <%= link_to "Explore", explore_path, class: "nav-link color" %>
      </li>
    </ul>
    <% if logged_in? %>
    <form class="form-inline mt-2 mt-md-0">
      <%= link_to "Log out", logout_path, method: :delete, class: "btn btn-sm btn-outline-danger" %>
    </form>
    <% end %>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<div class="container">
<h1>Edit Post</h1>

<%= form_for @post, url: post_path do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, placeholder: 'Update Title' %>
    </p>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body, placeholder: 'Update Content' %>
    </p>

    <p>
      <%= f.submit %><br>
    </p>

<% end %>
</div>

app/views/posts/index.html.erb
<div class="container">
<h1>My Blogs</h1>

<% @posts.each do |post| %>               
    <div class="card" style="width: 500px">
        <div class="col-lg-8">
            <div class="card-body">
                <h5 class="card-title"><%= post.title %></h5>
                <p class="card-text">"<%= post.body[0...15] %>..."</p>
                <%= link_to "Read More", post_path(post), class: "btn btn-primary" %>
            </div>                 
        </div>
    </div>
    <br></br>
<% end %>


<p>
<%= link_to 'Create New Post', new_post_path %>
</p>
</div>

app/views/posts/new.html.erb
<div class="container">
<h1>Add Post</h1>

<% if flash[:errors]%>
  <% flash[:errors].each do |error|%>
    <p style="color:red"><%= error%></p>
    <% end %>
  <% end %>

<%= form_for @post, url: posts_path do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, placeholder: 'Enter Title' %>
    </p>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body, placeholder: 'Enter Content' %>
      <% f.hidden_field :user_id %>
    </p>

    <p>
      <%= f.submit %><br>
    </p>

<% end %>

<p>
    <%= link_to "Cancel", posts_path, class: "btn btn-sm btn-outline-secondary" %>
</p>
</div>

app/views/posts/show.html.erb
<div class="container">
<h1> <%= @post.title%></h1>

<p>
  <%= @post.body%> 
</p>

<p>
    <%= link_to 'Update Blog', edit_post_path(@post) %> <br>
    <%= link_to 'Back to My Blogs', posts_path(@current_user) %>
</p>

<h2>Comments</h2>
Add Comments
<p>
    <% @post.comments.each do |comment|%>
        <div>
            <p><strong><%= comment.user.user_name %></strong>: <%= comment.body %><br> 
            Created: <small><%= comment.created_at %></small></p>
        </div>
        <% end %>
</p>

<div>
<%= form_for ([@post, @post.comments.build]) do |f| %>
   <% f.hidden_field :user_id %>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body, placeholder: 'Enter Comment' %>
    </p>

    <p>
      <%= f.submit %><br>
    </p>

<% end %>
</div>

<p>
    <%= button_to "Delete Post", destroy_post_path(@post)%>
</p>

</div>

app/views/users/new.html.erb
<div class="text-center mb-4">
<h1>Create Account</h1>

<% if flash[:errors]%>
  <% flash[:errors].each do |error|%>
    <p style="color:red"><%= error%></p>
    <% end %>
  <% end %>

<%= form_for @user do |f| %>
    <p>
      <%= f.label :user_name %><br>
      <%= f.text_field :user_name, placeholder: 'Enter Name' %>
    </p>

    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password, placeholder: 'Enter Password' %>
    </p>

    <p>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, placeholder: 'Re-Enter Password' %>
    </p>

    <p>
      <%= f.submit %><br>
    </p>

<% end %>
</div>

app/views/users/show.html.erb
<% @user.posts.each do |post| %>
    <ul>
     <li><%= link_to post.title, post_path(post)%></li><br>
    </ul> 
    <% end %>